name: Publish to PyPI

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary
  workflow_dispatch: # Allows manual triggering

jobs:
  publish:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Match your Poetry project version

      # Step 3: Install Poetry
      - name: Install Poetry
        run: |
          pip install poetry

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          poetry install

      # Step 5: Build the package
      - name: Build package
        run: |
          poetry build

      # Step 6: Publish to PyPI
      - name: Publish to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry publish --username __token__ --password $env:PYPI_API_TOKEN
